name: Publish to Test PyPI
on:
  push:
    tags:
      - '*.*.*'

jobs:
  test_pypi_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Run image
        uses: abatilo/actions-poetry@v2.1.4
      - name: Add test api key to .env file
        run: echo "MPH_API_KEY=${{ secrets.MPH_API_KEY}}" >> .env
      - run: poetry install
      - run: poetry config repositories.testpypi https://test.pypi.org/legacy/
      - run: poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_API_KEY }}
      - name: Publish package
        run: poetry publish --build -r testpypi
